- src/test/java/com/ordestiny/tdd/loop/WhileLoopTest.java
- src/test/java/loop/WhileLoopTest.java
> TDD on While Loop

- src/main/java/com/ordestiny/tdd/loop/ForLoop.java
- src/test/java/com/ordestiny/tdd/loop/ForLoopTest.java
> For loop TDD

- src/main/java/com/ordestiny/tdd/primitive/casting/Shorts.java
- src/test/java/com/ordestiny/tdd/conditional/IntegerEqualityTest.java
- src/test/java/com/ordestiny/tdd/primitive/casting/ShortsTest.java
This PR is about #28 
Please desconsider one to hacktoberfest or PR https://github.com/fengyuanyang/JavaTDD/pull/25 or this.
Thanks :)
> Primitive Casting Short

- .github/workflows/gradle.yml
- build.gradle
- config/checkstyle/checkstyle.xml
- src/main/java/com/ordestiny/tdd/conditional/IntegerEquality.java
- src/main/java/com/ordestiny/tdd/loop/ForLoop.java
- src/main/java/com/ordestiny/tdd/loop/WhileLoop.java
- src/main/java/com/ordestiny/tdd/primitive/casting/Shorts.java
- src/main/java/com/ordestiny/tdd/string/HelloWorld.java
- src/test/java/com/ordestiny/tdd/conditional/IntegerEqualityTest.java
- src/test/java/com/ordestiny/tdd/loop/ForLoopTest.java
- src/test/java/com/ordestiny/tdd/loop/WhileLoopTest.java
- src/test/java/com/ordestiny/tdd/primitive/casting/ShortsTest.java
- src/test/java/com/ordestiny/tdd/string/HelloWorldTest.java
> Add Google code style check CI

- build.gradle
> Ignore code style check warnings

- README.md
- src/main/java/com/ordestiny/tdd/lambda/functionalInterface/FunctionalInterface.java
- src/main/java/com/ordestiny/tdd/lambda/functionalInterface/Toy.java
- src/main/java/com/ordestiny/tdd/lambda/functionalInterface/ToyFactory.java
- src/main/java/com/ordestiny/tdd/lambda/functionalInterface/Worker.java
- src/test/java/com/ordestiny/tdd/lambda/functionalInterface/WorkerTest.java
Description
Added functional interface usage sample code
Checklist
100% coverage
> Add functional interface usage sample code

- src/main/java/com/ordestiny/tdd/conditions/Conditions.java
- src/test/java/com/ordestiny/tdd/Conditions/ConditionsTest.java
Signed-off-by: Stanislav Knot <sknot@redhat.com>
Added a class with basic conditions. Tests included.
> Conditions

- README.md
It says "project is getter big" and i corrected it to "project is getting bigger" ;)
> Fixed false spelling in README.md file

- src/main/java/com/ordestiny/tdd/loop/WhileLoopBreak.java
- src/main/java/com/ordestiny/tdd/loop/WhileLoopContinue.java
- src/test/java/com/ordestiny/tdd/loop/WhileLoopBreakTest.java
- src/test/java/com/ordestiny/tdd/loop/WhileLoopContinueTest.java
> Add WhileLoopBreak and WhileLoopContinue

- src/main/java/com/ordestiny/tdd/range/Range.java
- src/test/java/com/ordestiny/tdd/range/RangeTest.java
Add a new class/test class for Range kind.
Include method getAllPoints which will return array elements based on the input.
> Issue 56 get all points

- src/main/java/com/ordestiny/tdd/conditions/Switch.java
- src/test/java/com/ordestiny/tdd/Conditions/SwitchTest.java
Add TDD for switch
* Add TDD for switch
> issue #27 Add TDD for switch

- src/main/java/com/ordestiny/tdd/algorithms/SearchingAlgorithms.java
- src/test/java/com/ordestiny/tdd/algorithms/BinarySearchTest.java
Added binary search function calculating steps needed to find a given key.
> Issue #94 Add binary search function

- src/main/java/com/ordestiny/tdd/kata/BowlingGame.java
- src/test/java/com/ordestiny/tdd/kata/BowlingGameTest.java
Add kata bowling
* Add kata bowling
Resolves #69
> issue #69 Add kata bowling

- src/main/java/com/ordestiny/tdd/roman/num/converter/RomanNumConverter.java
- src/test/java/com/ordestiny/tdd/roman/num/converter/romanNumConverterTest.java
> convert from normal numbers to Roman Numerals

- src/main/java/com/ordestiny/tdd/kata/IntegerRangeContains.java
- src/test/java/com/ordestiny/tdd/kata/IntegerRangeContainsTest.java
> Add Kata - integer range contains.

- src/main/java/com/ordestiny/tdd/algorithms/SearchingAlgorithms.java
- src/test/java/com/ordestiny/tdd/algorithms/LinearSearchTest.java
> Add Linear Search

- src/main/java/com/ordestiny/tdd/kata/Equals.java
- src/test/java/com/ordestiny/tdd/kata/EqualsTest.java
> Add kata - Equals.

- .gitignore
- src/main/java/com/ordestiny/tdd/algorithms/TernarySearch.java
- src/test/java/com/ordestiny/tdd/algorithms/TernarySearchTest.java
Implementation of ternary search via TDD #116. Please can you review @fengyuanyang
> Implementation of ternary search

- src/main/java/com/ordestiny/tdd/kata/FooBarQix.java
- src/test/java/com/ordestiny/tdd/kata/FooBarQixTest.java
> [TDD] Kata - FooBarQix

- src/main/java/com/ordestiny/tdd/kata/StringCalculator.java
- src/test/java/com/ordestiny/tdd/kata/StringCalculatorTest.java
@fengyuanyang , first pass for the StringCalculator
Important Checklist
[x] I have written unit test first, make it red(fail first).
[x] I have then written logic code, make it green(success)
[x] I have tried to refactor my code, make it understandable(document my code)
> [TDD] Kata - String Calculator

- src/main/java/com/ordestiny/tdd/algorithms/FindMissing.java
- src/test/java/com/ordestiny/tdd/algorithms/FindMissingTest.java
> issue-99: FindMissing numbers

- .github/workflows/gradle.yml
- build.gradle
- src/main/java/com/ordestiny/tdd/Application.java
- src/main/resources/application.yml
1. exclude coverage check on Application.class
2. add actuator
> add: support for spring boot

- src/main/java/com/ordestiny/tdd/interview/linkedlist/LinkedListNode.java
- src/main/java/com/ordestiny/tdd/interview/linkedlist/LinkedListNodeUtil.java
- src/test/java/com/ordestiny/tdd/interview/linkedlist/LinkedListNodeUtilTest.java
below on left side
above on right side
and concatate
> issue-132: separate Linked List with partition value
